#CREATE DATABASE netflix;

CREATE TABLE TB_PERFIL (
	ID_PERFIL bigint(20) NOT NULL,
	DS_PERFIL varchar(255) NOT NULL
);

CREATE TABLE TB_USER (
	ID_USER bigint(20) NOT NULL,
	DS_EMAIL varchar(255) NOT NULL,
    UNIQUE(DS_EMAIL),
	DS_SENHA varchar(255) NOT NULL,
	DT_CRIACAO datetime NOT NULL,
	DT_ATUALIZACAO datetime NOT NULL,
	ID_PERFIL bigint(20) NOT NULL	
);